### PR TITLE
Plotting script improvements

### PR DESCRIPTION
**Pull request by amete**
This PR adds the new `nprocs` and `nthreads` variables to the list of possible variables in the plotting script. Also cleaned-up some obscurity in the naming of the network metrics.

### CODE REVIEW

**Comment by graeme-a-stewart** [comment]
Hi @amete - getting around to this a bit late, apologies!

I have to say that the output actually looks rather odd to me, running

```
./prmon_plot.py --input ~/tmp/prmon.txt --xvar wtime --yvar nprocs,nthreads --yunit 1
```

I get a y-axis label of "Count [1]", which is weird. I think the "[1]" should be suppressed.

**Comment by graeme-a-stewart** [comment]
Ping on this...

**Comment by amete** [comment]
Apologies for the belated response on this @graeme-a-stewart. I just updated the script so that we don't print out `[1]` in the axis labels. Could you take a look and let me know? Many thanks.

**Comment by graeme-a-stewart** [comment]
Grand - all looks good to me; merged.

**Pull request merged**
