### PR TITLE
Add HSF badge

### PR DESCRIPTION
**Pull request by graeme-a-stewart**
We got an HSF Project Affiliation badge!

### CODE REVIEW

**Comment by eduardo-rodrigues** [comment]
Great to see this @graeme-a-stewart! We should start a page for projects + badges on the HSF webpage. Let's discuss that soon ...

**Review by amete — APPROVED** [review]
This is great news, happily approving!

**Comment by graeme-a-stewart** [comment]
Oh bugger, the badge isn't working on the GH front page. It previewed ok, so I am not sure what's up.

**Comment by graeme-a-stewart** [comment]
OK, I managed to fix it - the recipe was to cache the SVG in the project (I put it in `doc`) and use a raw access URL to retrieve it, viz, https://raw.githubusercontent.com/HSF/prmon/refs/heads/main/doc/HSF-Bronze_Project-CD7F32.svg

**Pull request merged**
